[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Admin primero
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
